<a id = "1"></a>
<h1 style="padding:10px;background-color:rgb(70, 130, 180);opacity: 0.8;margin:0;color:white;font-family:calibri; font-size:200%;text-align:center;border-radius: 30px 50px;overflow:hidden;font-weight:500">TensorFlow Mastery Guide</h1>

Welcome to this comprehensive guide to mastering TensorFlow on Kaggle! This notebook is designed for beginners and will take you from the basics to advanced topics in TensorFlow, helping you to efficiently utilize TensorFlow principles in your Kaggle projects.

If you found this TensorFlow guide helpful and informative, please consider upvoting it, Your upvote helps others discover useful resources like this and supports me in creating more content.

<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<div class="list-group" id="list-tab" role="tablist">
  <h3 class="list-group-item list-group-item-action active" data-toggle="list" role="tab" aria-controls="home" style = "border:2px solid 'white';background-color:rgb(70, 130, 180)
;opacity:0.8; color:white; font-family:Verdana;text-align: center; font-size:100%;">Notebook Content</h3>
  <a class="list-group-item list-group-item-action" data-toggle="list" href="#1" role="tab" aria-controls="profile" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"><b>Introduction to TensorFlow</b><span class="badge badge-primary badge-pill">1</span></a>
  <a class="list-group-item list-group-item-action" data-toggle="list" href="#2" role="tab" aria-controls="messages" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"><b>Setting Up TensorFlow</b><span class="badge badge-primary badge-pill">2</span></a>
  <a class="list-group-item list-group-item-action" data-toggle="list" href="#3" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"><b>Basic Concepts</b><span class="badge badge-primary badge-pill">3</span></a>
  <a class="list-group-item list-group-item-action" data-toggle="list" href="#3.1" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Tensors<span class="badge badge-primary badge-pill">3.1</span></a> 
    <a class="list-group-item list-group-item-action" data-toggle="list" href="#3.2" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Operations<span class="badge badge-primary badge-pill">3.2</span></a> 
        <a class="list-group-item list-group-item-action" data-toggle="list" href="#4" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"><b>Building Neural Networks with Keras</b><span class="badge badge-primary badge-pill">4</span></a> 
        <a class="list-group-item list-group-item-action" data-toggle="list" href="#4.1" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Sequential API<span class="badge badge-primary badge-pill">4.1</span></a> 
        <a class="list-group-item list-group-item-action" data-toggle="list" href="#4.2" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Functional API<span class="badge badge-primary badge-pill">4.2</span></a> 
        <a class="list-group-item list-group-item-action" data-toggle="list" href="#5" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"><b>Training and Evaluation</b><span class="badge badge-primary badge-pill">5</span></a> 
        <a class="list-group-item list-group-item-action" data-toggle="list" href="#5.1" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Compiling Models<span class="badge badge-primary badge-pill">5.1</span></a> 
        <a class="list-group-item list-group-item-action" data-toggle="list" href="#5.2" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Training Models<span class="badge badge-primary badge-pill">5.2</span></a> 
        <a class="list-group-item list-group-item-action" data-toggle="list" href="#5.3" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Evaluating Models<span class="badge badge-primary badge-pill">5.3</span></a> 
          <a class="list-group-item list-group-item-action" data-toggle="list" href="#6" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"><b>Advanced Topics</b><span class="badge badge-primary badge-pill">6</span></a> 
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#6.1" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Custom Layers and Models<span class="badge badge-primary badge-pill">6.1</span></a> 
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#6.2" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Callbacks<span class="badge badge-primary badge-pill">6.2</span></a> 
    <a class="list-group-item list-group-item-action" data-toggle="list" href="#7" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"><b>Practical Kaggle Projects</b><span class="badge badge-primary badge-pill">7</span></a> 
    <a class="list-group-item list-group-item-action" data-toggle="list" href="#7.1" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Project 1: Image Classification<span class="badge badge-primary badge-pill">7.1</span></a> 
    <a class="list-group-item list-group-item-action" data-toggle="list" href="#7.2" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"></t>Project 2: Text Classification<span class="badge badge-primary badge-pill">7.2</span></a> 
<a class="list-group-item list-group-item-action" data-toggle="list" href="#8" role="tab" aria-controls="settings" target="_self" style = "color:grey; font-family:Verdana;text-align: left; font-size:100%;"><b>Conclusion</b><span class="badge badge-primary badge-pill">8</span></a>
</div>
</div>
</div>


<a id = "1"></a>
<h1 style="padding:10px;background-color:rgb(152, 255, 152);opacity: 0.8;margin:0;color:black;font-family:courier; font-size:200%;text-align:center;border-radius: 30px 50px;overflow:hidden;font-weight:500">1.Introduction to TensorFlow</h1>

TensorFlow is an open-source deep learning framework developed by Google.<br> It's widely used for machine learning tasks such as neural networks and can run on multiple CPUs and GPUs.

<a id = "2"></a>
<h1 style="padding:10px;background-color:rgb(152, 255, 152);opacity: 0.8;margin:0;color:black;font-family:courier; font-size:200%;text-align:center;border-radius: 30px 50px;overflow:hidden;font-weight:500">2.Setting Up TensorFlow</h1>

Kaggle kernels come pre-installed with TensorFlow. You can check the version of TensorFlow installed by running the following code:

In [1]:
import tensorflow as tf
print(tf.__version__)

2024-05-26 17:58:55.968950: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-26 17:58:55.969136: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-26 17:58:56.141486: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


2.15.0


<a id = "3"></a>
<h1 style="padding:10px;background-color:rgb(152, 255, 152);opacity: 0.8;margin:0;color:black;font-family:courier; font-size:200%;text-align:center;border-radius: 30px 50px;overflow:hidden;font-weight:500">3.Basic Concepts</h1>

<a id="3.1"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">3.1.Tensors</h2>


Tensors are the core data structure of TensorFlow. They are multi-dimensional arrays with a uniform type.

In [2]:
# Creating Tensors
import tensorflow as tf

# Scalar
scalar = tf.constant(7)
print("Scalar:", scalar)
print('-'*20)
# Vector
vector = tf.constant([10, 10])
print("Vector:", vector)
print('-'*20)
# Matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)
print('-'*20)
# Tensor
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Tensor:", tensor)

Scalar: tf.Tensor(7, shape=(), dtype=int32)
--------------------
Vector: tf.Tensor([10 10], shape=(2,), dtype=int32)
--------------------
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
--------------------
Tensor: tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


<a id="3.2"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">3.2. Operations</h2>


TensorFlow provides a rich set of operations for manipulating tensors.

In [3]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Addition
add = tf.add(a, b)
print("Addition:\n", add)
print('-'*20)
# Multiplication
mul = tf.matmul(a, b)
print("Multiplication:\n", mul)
print('-'*20)
# Element-wise multiplication
element_wise_mul = tf.multiply(a, b)
print("Element-wise multiplication:\n", element_wise_mul)


Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
--------------------
Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
--------------------
Element-wise multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


<a id = "4"></a>
<h1 style="padding:10px;background-color:rgb(152, 255, 152);opacity: 0.8;margin:0;color:black;font-family:courier; font-size:200%;text-align:center;border-radius: 30px 50px;overflow:hidden;font-weight:500">4.Building Neural Networks with Keras</h1>

Keras is TensorFlow's high-level API for building and training deep learning models.

<a id="4.1"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">4.1. Sequential API</h2>


<b>Sequential API:</b><br>
The Sequential API is a simple and straightforward way to build models in Keras. It allows you to create models layer-by-layer in a linear stack. This is best suited for plain stacks of layers where each layer has exactly one input tensor and one output tensor.<br>
<b>Key Points:</b><br>
* Ease of use: Very easy to use for simple, linear architectures.<br>
* Layer-by-layer construction: Layers are added sequentially.<br>
* Limitation: Not suitable for models with complex topologies (e.g., multi-input, multi-output models, or layers sharing outputs).

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

model.summary()

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 109,386 (427.29 KB)

 Trainable params: 109,386 (427.29 KB)

 Non-trainable params: 0 (0.00 B)

<a id="4.2"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">4.2.Functional API</h2>


<b>Functional API:</b><br>
The Functional API provides a more flexible way to build models, allowing for the creation of complex architectures such as multi-input, multi-output models, directed acyclic graphs, and models with shared layers.<br>

<b>Key Points:</b><br>
* Flexibility: Can handle complex model architectures.<br>
* Graph-like construction: Models are built as a graph of layers.<br>
* Reusability: Layers can be reused multiple times.

In [5]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

inputs = Input(shape=(784,))
x = Dense(128, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
outputs = Dense(10, activation='softmax')(x)

model = Model(inputs, outputs)
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 109,386 (427.29 KB)

 Trainable params: 109,386 (427.29 KB)

 Non-trainable params: 0 (0.00 B)

<a id = "5"></a>
<h1 style="padding:10px;background-color:rgb(152, 255, 152);opacity: 0.8;margin:0;color:black;font-family:courier; font-size:200%;text-align:center;border-radius: 30px 50px;overflow:hidden;font-weight:500">5.Training and Evaluation</h1>

<a id="5.1"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">5.1. Compiling Models</h2>


Before training, you need to compile the model, specifying the optimizer, loss function, and metrics.

In [6]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [7]:
# An ANN example of MNIST digit for showing the fit method
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Define model
model = Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile and train model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/opt/conda/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


<a id="5.2"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">5.2. Training Models</h2>


You can train the model using the fit method.

In [8]:
 history = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8608 - loss: 0.4813 - val_accuracy: 0.9559 - val_loss: 0.1568
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9596 - loss: 0.1361 - val_accuracy: 0.9667 - val_loss: 0.1172
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9759 - loss: 0.0831 - val_accuracy: 0.9707 - val_loss: 0.0979
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9809 - loss: 0.0628 - val_accuracy: 0.9678 - val_loss: 0.1025
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9857 - loss: 0.0459 - val_accuracy: 0.9745 - val_loss: 0.0856
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9894 - loss: 0.0367 - val_accuracy: 0.9768 - val_loss: 0.0822
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9923 - loss: 0.0277 - val_accuracy: 0.9743 - val_loss: 0.0918
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9940 - loss: 0.0219 

<a id="5.3"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">5.3. Evaluating Models</h2>


Evaluate the model on test data using the evaluate method.

In [9]:
# Assuming x_test, y_test are your test data and labels
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test loss: {test_loss}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9674 - loss: 0.1160
Test loss: 0.10018974542617798


<a id = "6"></a>
<h1 style="padding:10px;background-color:rgb(152, 255, 152);opacity: 0.8;margin:0;color:black;font-family:courier; font-size:200%;text-align:center;border-radius: 30px 50px;overflow:hidden;font-weight:500">6.Advanced Topics</h1>

<a id="6.1"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">6.1. Custom Layers and Models</h2>


You can create custom layers and models by subclassing tf.keras.layers.Layer and tf.keras.Model.

In [10]:
class CustomLayer(tf.keras.layers.Layer):
    def __init__(self, units=32):
        super(CustomLayer, self).__init__()
        self.units = units

    def build(self, input_shape):
        self.w = self.add_weight(shape=(input_shape[-1], self.units), initializer='random_normal', trainable=True)
        self.b = self.add_weight(shape=(self.units,), initializer='zeros', trainable=True)

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b

class CustomModel(tf.keras.Model):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.dense1 = CustomLayer(128)
        self.dense2 = CustomLayer(64)
        self.dense3 = tf.keras.layers.Dense(10, activation='softmax')

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return self.dense3(x)

model = CustomModel()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

<a id="6.2"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">6.2. Callbacks</h2>


Callbacks can be used to customize the training process.

In [11]:
model = Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile and train model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [12]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=3)

history = model.fit(x_train, y_train, epochs=50, batch_size=32, validation_split=0.2, callbacks=[early_stopping])

Epoch 1/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8658 - loss: 0.4820 - val_accuracy: 0.9543 - val_loss: 0.1596
Epoch 2/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9595 - loss: 0.1400 - val_accuracy: 0.9647 - val_loss: 0.1185
Epoch 3/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9729 - loss: 0.0907 - val_accuracy: 0.9704 - val_loss: 0.1004
Epoch 4/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9802 - loss: 0.0650 - val_accuracy: 0.9747 - val_loss: 0.0881
Epoch 5/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9850 - loss: 0.0498 - val_accuracy: 0.9743 - val_loss: 0.0909
Epoch 6/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9877 - loss: 0.0386 - val_accuracy: 0.9762 - val_loss: 0.0866
Epoch 7/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9905 - loss: 0.0305 - val_accuracy: 0.9747 - val_loss: 0.0899
Epoch 8/50
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9930 - loss: 0.0229 

<a id = "7"></a>
<h1 style="padding:10px;background-color:rgb(152, 255, 152);opacity: 0.8;margin:0;color:black;font-family:courier; font-size:200%;text-align:center;border-radius: 30px 50px;overflow:hidden;font-weight:500">7.Practical Kaggle Projects</h1>

<a id="7.1"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">7.1. Project 1: Image Classification</h2>


In this project, we will build a model to classify images from the MNIST dataset.<br>
To create a Convolutional Neural Network (CNN) for image classification using the MNIST dataset, we'll replace the Flatten layer with convolutional and pooling layers. Here's the updated code:

In [13]:
import tensorflow as tf

# Load data
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Reshape the data to fit the CNN input shape
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)

# Define model
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),  # Adding Dropout for regularization
    tf.keras.layers.Dense(10, activation='softmax')
])

# Compile and train model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

# Evaluate model
print(model.evaluate(x_test, y_test))

/opt/conda/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 31s 15ms/step - accuracy: 0.8621 - loss: 0.4491
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 29s 15ms/step - accuracy: 0.9651 - loss: 0.1167
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 41s 15ms/step - accuracy: 0.9739 - loss: 0.0846
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 41s 15ms/step - accuracy: 0.9792 - loss: 0.0689
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 29s 15ms/step - accuracy: 0.9827 - loss: 0.0553
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9832 - loss: 0.0518
[0.04257749766111374, 0.9861999750137329]


<a id="7.2"></a>
<h2 style="display:inline-block;padding:5px 20px;background-color:rgb(152, 255, 152);opacity:0.8;margin:0;color:black;font-family:courier;font-size:150%;text-align:center;border-radius:15px 25px;overflow:hidden;font-weight:500">7.2. Project 2: Text Classification</h2>


In this project, we will build a model to classify text data from the IMDB datase

In [14]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D, Dropout

# Load data
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=10000)

# Preprocess data
maxlen = 256
x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = tf.keras.preprocessing.sequence.pad_sequences(x_test, maxlen=maxlen)

# Define model
model = Sequential([
    Embedding(input_dim=10000, output_dim=16),
    GlobalAveragePooling1D(),
    Dense(16, activation='relu'),
    Dropout(0.5),  # Adding dropout for regularization
    Dense(1, activation='sigmoid')
])

# Print model summary
model.summary()

# Compile and train model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=10, batch_size=512, validation_split=0.2)

# Evaluate model
print("Model Evaluation: ",model.evaluate(x_test, y_test))


17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ ?                      │   0 (unbuilt) │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.5225 - loss: 0.6925 - val_accuracy: 0.6930 - val_loss: 0.6876
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.6135 - loss: 0.6852 - val_accuracy: 0.7258 - val_loss: 0.6731
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.6644 - loss: 0.6679 - val_accuracy: 0.7674 - val_loss: 0.6444
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7040 - loss: 0.6381 - val_accuracy: 0.7790 - val_loss: 0.6016
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7431 - loss: 0.5954 - val_accuracy: 0.8014 - val_loss: 0.5497
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7765 - loss: 0.5429 - val_accuracy: 0.8188 - val_loss: 0.4976
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8019 - loss: 0.4940 - val_accuracy: 0.8328 - val_loss: 0.4534
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8212 - loss: 0.4558 - val_accuracy: 0.8524 - v

<a id = "8"></a>
<h1 style="padding:10px;background-color:rgb(152, 255, 152);opacity: 0.8;margin:0;color:black;font-family:courier; font-size:200%;text-align:center;border-radius: 30px 50px;overflow:hidden;font-weight:500">8.Conclusion and Next Steps</h1>

Congratulations on completing this TensorFlow guide! You've learned the fundamentals of TensorFlow and how to apply them effectively. From basic concepts to advanced techniques, you've gained valuable insights that will help you in your machine learning journey.

Remember, practice makes perfect. Keep experimenting with different models, datasets, and techniques. Kaggle projects, competitions are a great way to apply what you've learned and challenge yourself further.

If you found this guide helpful, please consider upvoting it on Kaggle to support the author and help others discover it.

Thank you for reading, and happy coding!